lang: ruby
rvm: 2.6
dist: xenial
sudo: required
env:
  global:
    - PATH=$HOME/.local/bin:$PATH

before_install:
  - pip install --user awscli
  - pip install --user aws-sam-cli
  - gem update --system
  - gem install bundler

script: make deploy