[package]
name = "api"
version = "0.1.0"
authors = ["Dawson Israel <dawfre@amazon.com>"]
edition = "2018"

[dependencies]
lambda_runtime = "0.2.1"
lambda_http = "0.1.1"
serde = "*"
serde_derive = "*"
simple_logger = "*"
simple-error = "*"
log = "*"