default: &default
  adapter: sqlite3
  encoding: utf8
  pool: <%= ENV["DB_POOL"] || 5  %>
  database: <%= ENV['DB_NAME'] || 'api_development' %>
  username: <%= ENV['DB_USER'] || 'root' %>
  password: <%= ENV['DB_PASS'] %>
  host: <%= ENV["DB_HOST"] %>
  url: <%= ENV['DATABASE_URL'] %> # takes higher precedence than other settings

development:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'api_development' %>

test:
  <<: *default
  database: api_test

production:
  <<: *default
  database: api_production
  url: <%= ENV['DATABASE_URL'] %>
