name: CD

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: rstudio/r-base:3.6-xenial
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}        
    - name: Install System Dependencies
      run: |
          sudo apt-get update && apt-get install -y --no-install-recommends \
          docker \
          git \
          libxml2-dev \
          libssl-dev \
          && apt-get clean -y \
          && curl -fsSL https://get.docker.com -o get-docker.sh \
          && sh get-docker.sh
    - name: Build
      run: docker run -v ${PWD}:/code softprops/lambda-rust
    - name: Install CDK
      run: npm --prefix cdk install cdk
    - name: Build CDK
      run: npm run build --prefix cdk
    - name: AWS CDK Deploy
      uses: MikeBild/aws-cdk-js-github-action@1.0.0
      with:
        args: deploy *-stack --app 'node cdk/index' --require-approval=never
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}